# -*- coding: utf-8 -*-
"""Config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDugmjeCvhXHT451gwch9ImTKpXCApfz
"""

from easydict import EasyDict as edict
import json

config = edict()
config.TRAIN = edict()
config.TRAIN.batch_size = 16  # according for GPU memory allocation
config.TRAIN.lr_init = 1e-4
config.TRAIN.beta1 = 0.9

## Initialising the G
config.Train.n_epoch_init = 100


## adversarial learning(SRGAN)
config.TRAIN.n_epoch = 100
config.TRAIN.lr_deacy = 0.1
config.TRAIN.decay_every = int(config.TRAIN.n_epoch /2)


#Train set location
config.TRAIN.hr_img_path = 'DIV2K/DIV2K_train_HR'
config.TRAIN.lr_img_path = 'DIV2K/DIV2K_train_LR_bicubic/X4/h'


config.VALID = edict()

#test set loaction

config.VALID.hr_img_path = 'DIV2K/DIV2K_train_HR'
config.VALID.lr_img_path = 'DIV2K/DIV2K_train_LR_bicubic/X4/h'


def log_config(filename,cfg):
  with open(filename, 'w') as f:
    f.write("===================\n")
    f.write(json.dumps(cfg, indent = 4))
    f.write("====================\n")